# Generated by Django 5.2.17 on 2026-09-11 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0006_remove_campo_firma_unico_por_destinatario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DOCUMENTO_CREADO', 'Documento creado'), ('DOCUMENTO_ENVIADO', 'Documento enviado'), ('DOCUMENTO_VISUALIZADO', 'Documento visualizado'), ('FIRMA_COMPLETADA', 'Firma completada'), ('DOCUMENTO_RECHAZADO', 'Documento rechazado'), ('PROCESO_FINALIZADO', 'Proceso finalizado')], db_index=True, max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('informacion_adicional', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to='documentos.documento')),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to='documentos.enviodocumento')),
            ],
            options={
                'verbose_name': 'evento de auditoría',
                'verbose_name_plural': 'eventos de auditoría',
                'ordering': ('fecha_hora', 'id'),
                'indexes': [models.Index(fields=['documento', 'fecha_hora'], name='aud_doc_fecha_idx'), models.Index(fields=['envio', 'fecha_hora'], name='aud_env_fecha_idx')],
            },
        ),
    ]
