# Generated by Django 5.2.17 on 2026-10-09 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('documentos', '0008_documento_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoauditoria',
            name='usuario_afectado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_administrativos_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventoauditoria',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to='documentos.documento'),
        ),
        migrations.AlterField(
            model_name='eventoauditoria',
            name='tipo',
            field=models.CharField(choices=[('DOCUMENTO_CREADO', 'Documento creado'), ('DOCUMENTO_ENVIADO', 'Documento enviado'), ('DOCUMENTO_VISUALIZADO', 'Documento visualizado'), ('FIRMA_COMPLETADA', 'Firma completada'), ('DOCUMENTO_RECHAZADO', 'Documento rechazado'), ('PROCESO_FINALIZADO', 'Proceso finalizado'), ('USUARIO_ORG_MODIFICADA', 'Organización de usuario modificada')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='eventoauditoria',
            index=models.Index(fields=['usuario_afectado', 'fecha_hora'], name='aud_usuario_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoauditoria',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('documento__isnull', False), ('usuario_afectado__isnull', True)), models.Q(('documento__isnull', True), ('envio__isnull', True), ('usuario_afectado__isnull', False)), _connector='OR'), name='auditoria_contexto_valido'),
        ),
    ]
