# Generated by Django 5.2.17 on 2026-09-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0003_alter_destinatariodocumento_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.BinaryField(max_length='max')),
                ('formato', models.CharField(default='image/png', editable=False, max_length=30)),
                ('consentimiento', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to='documentos.destinatariodocumento')),
            ],
            options={
                'verbose_name': 'firma',
                'verbose_name_plural': 'firmas',
                'ordering': ('-fecha_firma',),
                'constraints': [models.CheckConstraint(condition=models.Q(('consentimiento', True)), name='firma_requiere_consentimiento')],
            },
        ),
    ]
