# Generated by Django 5.2.17 on 2026-09-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='imagen',
            field=models.BinaryField(),
        ),
    ]
