# Generated by Django 5.2.17 on 2026-09-08 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0002_alter_firma_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='metodo',
            field=models.CharField(choices=[('PERFIL', 'Firma guardada'), ('DIBUJADA', 'Firma dibujada')], default='DIBUJADA', max_length=10),
        ),
        migrations.CreateModel(
            name='FirmaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.BinaryField(max_length='max')),
                ('formato', models.CharField(editable=False, max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'firma de perfil',
                'verbose_name_plural': 'firmas de perfil',
            },
        ),
    ]
