# Generated by Django 5.2.17 on 2026-09-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0003_firma_metodo_firmaperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmaperfil',
            name='imagen',
            field=models.BinaryField(),
        ),
    ]
