# Generated by Django 5.2.17 on 2026-09-07 14:54

import django.core.validators
import django.db.models.deletion
import documentos.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf']), documentos.validators.validar_pdf])),
                ('nombre_original', models.CharField(max_length=255)),
                ('tamano', models.PositiveBigIntegerField()),
                ('hash_sha256', models.CharField(editable=False, max_length=64)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ('-fecha_creacion',),
            },
        ),
    ]
