# Generated by Django 5.2.17 on 2026-09-07 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado')], default='ENVIADO', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='documentos.documento')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'envio de documento',
                'verbose_name_plural': 'envios de documentos',
                'ordering': ('-fecha_envio',),
            },
        ),
        migrations.CreateModel(
            name='DestinatarioDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VISTO', 'Visto')], default='PENDIENTE', max_length=20)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_visualizacion', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='documentos.enviodocumento')),
            ],
            options={
                'verbose_name': 'destinatario de documento',
                'verbose_name_plural': 'destinatarios de documentos',
                'ordering': ('-fecha_agregado',),
                'constraints': [models.UniqueConstraint(fields=('envio', 'usuario'), name='destinatario_unico_por_envio')],
            },
        ),
    ]
