# Generated by Django 5.2.17 on 2026-09-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_enviodocumento_destinatariodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatariodocumento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VISTO', 'Visto'), ('FIRMADO', 'Firmado')], default='PENDIENTE', max_length=20),
        ),
    ]
