# Generated by Django 5.2 on 2026-09-07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0003_alter_destinatariodocumento_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enviodocumento",
            name="estado",
            field=models.CharField(choices=[("PREPARACION", "En preparación"), ("ENVIADO", "Enviado")], default="ENVIADO", max_length=20),
        ),
        migrations.AlterField(
            model_name="destinatariodocumento",
            name="estado",
            field=models.CharField(choices=[("BORRADOR", "Borrador"), ("PENDIENTE", "Pendiente"), ("VISTO", "Visto"), ("FIRMADO", "Firmado")], default="PENDIENTE", max_length=20),
        ),
        migrations.CreateModel(
            name="CampoFirma",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pagina", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("x", models.DecimalField(decimal_places=6, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("1"))])),
                ("y", models.DecimalField(decimal_places=6, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("1"))])),
                ("ancho", models.DecimalField(decimal_places=6, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal("0.000001")), django.core.validators.MaxValueValidator(Decimal("1"))])),
                ("alto", models.DecimalField(decimal_places=6, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal("0.000001")), django.core.validators.MaxValueValidator(Decimal("1"))])),
                ("destinatario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="campos_firma", to="documentos.destinatariodocumento")),
            ],
            options={
                "verbose_name": "campo de firma",
                "verbose_name_plural": "campos de firma",
                "ordering": ("pagina", "id"),
                "constraints": [
                    models.UniqueConstraint(fields=("destinatario",), name="campo_firma_unico_por_destinatario"),
                    models.CheckConstraint(condition=models.Q(("x__gte", 0), ("x__lte", 1), ("y__gte", 0), ("y__lte", 1)), name="campo_firma_posicion_normalizada"),
                    models.CheckConstraint(condition=models.Q(("alto__gt", 0), ("alto__lte", 1), ("ancho__gt", 0), ("ancho__lte", 1)), name="campo_firma_dimension_normalizada"),
                    models.CheckConstraint(condition=models.Q(("pagina__gte", 1)), name="campo_firma_pagina_positiva"),
                    models.CheckConstraint(condition=models.Q(("x__lte", models.Value(1) - models.F("ancho"))), name="campo_firma_dentro_ancho_pagina"),
                    models.CheckConstraint(condition=models.Q(("y__lte", models.Value(1) - models.F("alto"))), name="campo_firma_dentro_alto_pagina"),
                ],
            },
        ),
    ]
