# Generated by Django 5.2 on 2026-09-09

import django.db.models.deletion
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0004_estados_preparacion_campofirma"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoResultado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archivo", models.FileField(upload_to=documentos.models.ruta_documento_resultado)),
                ("hash_sha256", models.CharField(editable=False, max_length=64)),
                ("tamano", models.PositiveBigIntegerField(editable=False)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                ("envio", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="resultado", to="documentos.enviodocumento")),
            ],
            options={
                "verbose_name": "documento resultado",
                "verbose_name_plural": "documentos resultado",
                "ordering": ("-fecha_generacion",),
            },
        ),
    ]
