# Generated by Django 5.2 on 2026-09-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0005_documentoresultado"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="campofirma",
            name="campo_firma_unico_por_destinatario",
        ),
    ]
