# Generated by Django 5.2 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0006_remove_campo_firma_unico_por_destinatario"),
    ]

    operations = [
        migrations.AddField(
            model_name="campofirma",
            name="etiqueta",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="campofirma",
            name="fecha_completado",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campofirma",
            name="requerido",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campofirma",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("FIRMA", "Firma"),
                    ("NOMBRE", "Nombre"),
                    ("FECHA", "Fecha"),
                    ("TEXTO", "Texto"),
                    ("INICIALES", "Iniciales"),
                    ("CHECKBOX", "Checkbox"),
                ],
                default="FIRMA",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="campofirma",
            name="valor",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="campofirma",
            options={
                "ordering": ("pagina", "id"),
                "verbose_name": "campo de documento",
                "verbose_name_plural": "campos de documento",
            },
        ),
    ]
