# Generated by Django 5.2.17 on 2026-09-03 15:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'comite',
                'verbose_name_plural': 'comites',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('VICEPRESIDENTE', 'Vicepresidente'), ('SECRETARIO', 'Secretario'), ('TESORERO', 'Tesorero'), ('MIEMBRO', 'Miembro')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('es_directivo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('codigo__in', ('PRESIDENTE', 'VICEPRESIDENTE', 'SECRETARIO', 'TESORERO')), ('es_directivo', True)), models.Q(('codigo', 'MIEMBRO'), ('es_directivo', False)), _connector='OR'), name='cargo_codigo_directivo_valido')],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cargo', models.ForeignKey(db_column='cargo_codigo', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.cargo', to_field='codigo')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.comite')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('cargo', 'PRESIDENTE')), fields=('comite',), name='un_presidente_por_comite'), models.UniqueConstraint(condition=models.Q(('cargo', 'VICEPRESIDENTE')), fields=('comite',), name='un_vicepresidente_por_comite'), models.UniqueConstraint(condition=models.Q(('cargo', 'SECRETARIO')), fields=('comite',), name='un_secretario_por_comite'), models.UniqueConstraint(condition=models.Q(('cargo', 'TESORERO')), fields=('comite',), name='un_tesorero_por_comite')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
