# Generated by Django 5.2.17 on 2026-09-03 15:41

from django.db import migrations


def cargar_cargos(apps, schema_editor):
    Cargo = apps.get_model("usuarios", "Cargo")
    Cargo.objects.bulk_create(
        [
            Cargo(codigo="PRESIDENTE", nombre="Presidente", es_directivo=True),
            Cargo(
                codigo="VICEPRESIDENTE",
                nombre="Vicepresidente",
                es_directivo=True,
            ),
            Cargo(codigo="SECRETARIO", nombre="Secretario", es_directivo=True),
            Cargo(codigo="TESORERO", nombre="Tesorero", es_directivo=True),
            Cargo(codigo="MIEMBRO", nombre="Miembro", es_directivo=False),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [migrations.RunPython(cargar_cargos, migrations.RunPython.noop)]
