# Generated by Django 5.2.17 on 2026-09-04 15:46

import usuarios.models
from django.db import migrations, models


def preparar_correos_institucionales(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    usuarios = list(Usuario.objects.order_by("pk"))

    def correo_institucional(valor):
        email = (valor or "").strip().casefold()
        _, separator, domain = email.rpartition("@")
        return email if separator and domain == "adicla.org.gt" else None

    candidatos = {
        usuario.pk: correo_institucional(usuario.email)
        or correo_institucional(usuario.username)
        for usuario in usuarios
    }
    reservados = {email for email in candidatos.values() if email}
    usados = set()

    for usuario in usuarios:
        email = candidatos[usuario.pk]

        if not email or email in usados:
            email = f"usuario-{usuario.pk}@adicla.org.gt"
            suffix = 1
            while email in reservados or email in usados:
                email = f"usuario-{usuario.pk}-{suffix}@adicla.org.gt"
                suffix += 1

        Usuario.objects.filter(pk=usuario.pk).update(email=email)
        usados.add(email)


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_cargar_cargos_iniciales"),
    ]

    operations = [
        migrations.RunPython(
            preparar_correos_institucionales,
            migrations.RunPython.noop,
        ),
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="username",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[usuarios.models.validate_institutional_email],
                verbose_name="correo electrónico",
            ),
        ),
    ]
