# Generated by Django 5.2.17 on 2026-09-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_configurar_comites_oficiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_ultimo_envio_verificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_verificacion_email',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='version_verificacion_email',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
